protoc --go_out=internal/adapters/framework/left/gRPC --proto_path=internal/adapters/framework/left/gRPC/proto internal/adapters/framework/left/gRPC/proto/number_msg.proto

protoc --go_out=internal/adapters/framework/left/gRPC --proto_path=internal/adapters/framework/left/gRPC/proto internal/adapters/framework/left/gRPC/proto/number_msg.proto